Document: qt6base
Title: Debian qt6base Manual
Author: <insert document author here>
Abstract: This manual describes what qt6base is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/qt6base/qt6base.sgml.gz

Format: postscript
Files: /usr/share/doc/qt6base/qt6base.ps.gz

Format: text
Files: /usr/share/doc/qt6base/qt6base.text.gz

Format: HTML
Index: /usr/share/doc/qt6base/html/index.html
Files: /usr/share/doc/qt6base/html/*.html
