name: Build Debian Package

on: push

jobs:
  build:
    permissions:
      id-token: write
      contents: read
      attestations: write
    strategy:
      fail-fast: false
      matrix:
        arch: ['arm64', 'amd64', 'armhf']
    uses: torizon/torizon-deb-ci/.github/workflows/toradex-deb-ci.yml@main
    with:
      arch: ${{ matrix.arch }}
      docker-image: debian:bookworm
      package-name: weston
      run-attestation: true
      run-piuparts: false
      upload-artifacts: true
